# .air.toml
# Config file for the Air live-reloader: https://github.com/air-verse/air

# The root directory of your project.
root = "."
# The directory where the temporary binary will be stored.
tmp_dir = "tmp"

[build]
# This is the crucial part. We tell Air to build the package located in ./cmd/api
# and output the binary to ./tmp/main.
cmd = "go build -o ./tmp/main ./cmd/api"
# The binary that Air will execute after a successful build.
bin = "tmp/main"
# File extensions to watch for changes.
include_ext = ["go", "tpl", "tmpl", "html"]
# Directories to exclude from watching. We must exclude tmp_dir.
exclude_dir = ["tmp", "vendor"]
# Add a small delay to prevent rapid-fire rebuilds.
delay = 1000 # ms
# Stop the old binary if the new build fails.
stop_on_error = true

[log]
time = true

[misc]
# Clean up the tmp directory when Air exits.
clean_on_exit = true